

defaults:
  - base_config
  - override network: polaris
  - override framework: torch
  - _self_

data: 
  downsample: 1
  synthetic: True
  aux_file: cosmic_tagging_light.h5
  data_directory: /nfs/anoop/code/CosmicTagger/example_data/
  file: cosmic_tagging_light.h5

run:
    distributed: True
    minibatch_size: 8